{% set name = "google-cloud-build" %}
{% set version = "3.3.0" %}
{% set sha256 = "a90000d52bf1751d08f2639cc6ccc2030bb3c18dc3a01c02830567b6573a3562" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip >=18.1
  run:
    - python >=3.6
    - google-api-core-grpc >=1.22.2,<2.0.0dev
    - proto-plus >=0.4.0
    - packaging >=14.3

test:
  imports:
    - grpc
    - google.cloud.devtools.cloudbuild
    - google.cloud.devtools.cloudbuild_v1

about:
  home: https://github.com/googleapis/python-cloudbuild
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google Cloud Build API client library
  description: "Google Cloud Build API is a Google Cloud service that lets client applications create and manage builds on Google Cloud Platform. Cloud Build lets you build software quickly across all languages. Get complete control over defining custom workflows for building, testing, and deploying across multiple environments\
    \ such as VMs, serverless, Kubernetes, or Firebase.\nSee the [quick start guide](https://googleapis.dev/python/cloudbuild/latest/index.html#quick-start)."

  doc_url: https://googleapis.dev/python/cloudbuild/latest/index.html
  dev_url: https://github.com/googleapis/python-cloudbuild

extra:
  recipe-maintainers:
    - parthea
