{% set name = "google-cloud-build" %}
{% set version = "3.30.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7d8d85289108abe889774ff725623b5fe4b2545519992dc7d48a17d8eceaf939

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - google-api-core >=1.34.1,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,!=2.10.*
    - google-api-core-grpc
    - google-auth >=2.14.1,<3.0.0dev,!=2.24.0,!=2.25.0
    - grpc-google-iam-v1 >=0.12.4,<1.0.0dev
    # more restrictive version for python 3.13
    - proto-plus >=1.25.0,<2.0.0dev
    - protobuf >=3.20.2,<6.0.0dev,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5

test:
  imports:
    - grpc
    - google.cloud.devtools.cloudbuild
    - google.cloud.devtools.cloudbuild_v1
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-build
  summary: Google Cloud Build API client library
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: "Google Cloud Build API is a Google Cloud service that lets client applications create and manage builds on Google Cloud Platform. Cloud Build lets you build software quickly across all languages. Get complete control over defining custom workflows for building, testing, and deploying across multiple environments
    such as VMs, serverless, Kubernetes, or Firebase.\nSee the [quick start guide](https://googleapis.dev/python/cloudbuild/latest/index.html#quick-start)."

  doc_url: https://googleapis.dev/python/cloudbuild/latest/index.html
  dev_url: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-build

extra:
  recipe-maintainers:
    - xylar
    - parthea
